### ISSUE TITLE
mvdr_model.py issue

### ISSUE THREAD

**Issue by rolandhartanto21** [hangtingchen/Beam-Guided-TasNet#8]
Dear Authors of Beam-Guided TasNet,

I would like to ask about an issue that I found when I ran run.sh script.
The following is the error.
```
File "/work/roland/research/source_separation/Beam-Guided-TasNet/mvdr_model.py", line 184, in forward
    est_filt = est_filt.permute(0,3,4,2,1) # B*S C C F T
RuntimeError: permute(sparse_coo): number of dimensions in the tensor input does not match the length of the desired ordering of dimensions i.e. input.dim() = 4 is not equal to len(dims) = 5
```
The shape of the MVDR filter looks different from what is specified in the comment. Could you help me with this issue?
Thank you.

**Comment by rolandhartanto21** [comment]
It seems when I used the torch solver, the issue above occurred. When I used the other one, the problem did not occur.

```
if use_torch_solver and is_torch_1_1_plus:
    # torch.solve is required, which is only available after pytorch 1.1.0+
    numerator = FC.solve(psd_s, psd_n)[0]
else:
    numerator = FC.matmul(psd_n.inverse2(), psd_s)
```

**Comment by hangtingchen** [comment]
This bug was caused by an unknown dimension flattening or a dim=1 squeezed. Since you can run the code with torch.solve, I recommend printing the feature "numerator " dimension of the one outputted by torch.solve. And reshape the one outputted by inverse2()  according to the right dimension. I guess "unsqueeze" can solve the problem.

**Comment by rolandhartanto21** [comment]
Thank you for your answer. I will try it later.
